# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.0"

HERE = File.dirname(__FILE__)
ENV['ANSIBLE_CONFIG'] = "#{HERE}/../ansible/ansible.cfg"

# Workaround for ssh problem with ED25519 curve
# SSH not up: #<Vagrant::Errors::NetSSHException: An error occurred in the underlying SSH library that Vagrant uses.
# curve name mismatched
if ENV.has_key?('SSH_AUTH_SOCK')
    ENV.delete('SSH_AUTH_SOCK')
end

DOMAIN="ipatests.local"

Vagrant.configure(2) do |config|
    config.vm.box = "cheimes/freeipa44-f24"

    # no rsync, Ansible playbook syncs files manually
    config.vm.synced_folder ".", "/vagrant", disabled: true

    if Vagrant.has_plugin?("vagrant-hostmanager")
        config.hostmanager.enabled = true
        config.hostmanager.manage_host = true
        config.hostmanager.manage_guest = false
    end

    config.vm.define "ipatestmaster" do |host|
        host.vm.hostname = "master.#{DOMAIN}"
        host.vm.provider :libvirt do |domain|
            domain.memory = 1536
            domain.cpus = 2
        end

        host.vm.provision "ansible" do |ansible|
            ansible.limit = "all"
            ansible.playbook = "../ansible/ipa-playbook.yml"
            ansible.groups = {
                "ipaserver_master" => ["ipatestmaster"],
                "ipa_tests" => ["ipatestmaster"],
            }
            ansible.verbose = 'vv'
            ansible.skip_tags = [
                'dummy',
            ]
            # ansible.tags = ['bootstrap', 'common', 'ipa-tests']
            ansible.extra_vars = {
                "ipa_data_dir" => HERE + '/inventory',
                "ipa_script_dir" => HERE + '/bin',
                "ipa_rpm_dir" => HERE + '/rpms',
                "package_install" => false,
                "package_upgrade" => false,
                "custom_rpms" => false,
                "coprs_enabled" => [
                    # "@freeipa/freeipa-master",
                ],
            }
        end
    end
end
