#!/bin/sh
set -e

# https://copr-be.cloud.fedoraproject.org/results/@freeipa/freeipa-4-3/pubkey.gpg
cat > /tmp/freeipa-pubkey.gpg << EOF
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2

mQENBFbZjukBCACqi/riCCTg8j8HWGG2RozBuUmxwry3EXlL2iKXtjxEgqxB4HsU
DXGZedrBXoVw3sKozqPAcu838FEnUKxBpursAJMm2hQnRGKlcL+AmPV7EVdmV7gA
ab0VrMeqCVk4sTuhenv5BHKn1UIbraduamdEYPPQvtUnDxegmAjhgbdE3oY673nL
Tlpoj2/JMZ2+JVY7U9YeHND7YU6Yqj4Oo2vO4ndDoLyivKanWyvYLjEI0u+kztp7
bjAlzmG+vbQNO2GAX4dZjRn/LlUix7640AqtbVyIqCo9L2Tj/XqFRXGbDPgs/sFh
EncNyg1JTLMnsZMTGkl0FJJoglTo7PjFlKD/ABEBAAG0SEBmcmVlaXBhX2ZyZWVp
cGEtNC0zIChOb25lKSA8QGZyZWVpcGEjZnJlZWlwYS00LTNAY29wci5mZWRvcmFo
b3N0ZWQub3JnPokBPwQTAQgAKQUCVtmO6QIbLwUJCWYBgAcLCQgHAwIBBhUIAgkK
CwQWAgMBAh4BAheAAAoJEGkrtLBC/LPhwh8H/30oZFihTrHqH9aEXqbj68r67OAU
Dife4P2g7Vh7L6/WMtQq2GI7bfLzXymFltA2F6Rt166OeM1BlJGrBchiqUjJIfCH
Y4XTA2v8Am1CJQnzOErAh0rkhGKrkxLvEc7Xqw+hvlClthRLOVM/M6sBW1r+oeZH
7LsGzJw4Emfdqbnn3P1GwzGVE0gBp5n8fa+UyzkZBhkcjCiTo4rE1F+CEh5iaIih
541rnWocbeEcpGDR+3wNV3jt14+EsTq+dw2+Y4Ff4T/ctp5hN2+F1JtCB417jQxH
T5GMP6IBr+ma/JjrwMpRugoZ7SGKQSVrw9z0VxSjkJc01hmhVH37o7Mjysc=
=xrrl
-----END PGP PUBLIC KEY BLOCK-----
EOF

rpm --import /tmp/freeipa-pubkey.gpg

dnf copr enable -y @freeipa/freeipa-4-3

