#!/bin/sh
# Install FreeIPA and additional packages for demo setup
# Christian Heimes <cheimes@redhat.com>
set -e

# Apache HTTP, gssapi auth and lookup identity with SSSD info pipe
HTTPD_PKG="httpd mod_auth_gssapi mod_authnz_pam mod_intercept_form_submit \
    mod_lookup_identity libsss_simpleifp sssd-dbus mod_nss mod_session \
    mod_wsgi"

# Ipsilon identity provider and service point with Apache mod_auth_mellon
IPSILON_PKG="ipsilon ipsilon-client ipsilon-saml2 ipsilon-openid \
    ipsilon-persona ipsilon-authform ipsilon-infosssd ipsilon-tools-ipa \
    ipsilon-authgssapi ipsilon-authfas ipsilon-authpam"

# Samba server and client
SAMBA_PKG="samba samba-client sssd-libwbclient"

# OpenConnect VPN demo
OCSERV_PKG="ocserv openconnect bridge-utils"

# NFS 
MISC_PKG="nfs-utils"


if [ -x /usr/bin/dnf ]; then
    PKGMGR=dnf
else
    PKGMGR=yum
fi


. /etc/os-release

case $ID in
  centos|rhel)
    IPA_PKG="ipa-client ipa-server ipa-server-dns"
  ;;
  fedora)
    IPA_PKG="freeipa-client freeipa-server freeipa-server-dns"
  ;;
  *)
    echo "Unsupported distribution $ID"
    exit 1
  ;;
esac

$PKGMGR install -y --best $IPA_PKG $OCSERV_PKG $SAMBA_PKG $HTTPD_PKG $IPSILON_PKG $NFS_PKG

