# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.0"

HERE = File.dirname(__FILE__)
ENV['ANSIBLE_CONFIG'] = "#{HERE}/../ansible/ansible.cfg"
# virtual env for Ansible 2
# ENV['PATH'] = "#{HERE}/../venv/bin:" + ENV['PATH']

# Workaround for ssh problem with ED25519 curve
# SSH not up: #<Vagrant::Errors::NetSSHException: An error occurred in the underlying SSH library that Vagrant uses.
# curve name mismatched
if ENV.has_key?('SSH_AUTH_SOCK')
    ENV.delete('SSH_AUTH_SOCK')
end

DOMAIN="pki.example"

Vagrant.configure(2) do |config|
    config.vm.box = "cheimes/dogtag-f23"

    config.vm.provider :libvirt do |domain|
        domain.memory = 1024
        domain.cpus = 2
    end

    # no rsync, Ansible playbook syncs required files manually
    config.vm.synced_folder ".", "/vagrant", disabled: true

    if Vagrant.has_plugin?("vagrant-hostmanager")
        config.hostmanager.enabled = true
        config.hostmanager.manage_host = true
        config.hostmanager.manage_guest = false
    end

    config.vm.define "pki_server" do |server|
        server.vm.hostname = "dogtag.#{DOMAIN}"
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "../ansible/pki-playbook.yml"
        ansible.groups = {
            "pki_server" => ["pki_server"],
        }
        #ansible.verbose = 'vv'
        # pki-install: skip installation (setup-ds, pkispawn)
        ansible.skip_tags = [
            #'pki-install',
            'dummy',
        ]
        ansible.extra_vars = {
            "ipa_data_dir" => HERE + '/inventory',
            "ipa_script_dir" => HERE + '/bin',
            "ipa_rpm_dir" => HERE + '/rpms',
            "package_install" => false,
            "package_upgrade" => false,
            "coprs_enabled" => [],
        }
    end
end
