# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.0"

Vagrant.configure(2) do |config|
    config.vm.box = "f23"
    config.vm.box_url = "http://download.fedoraproject.org/pub/fedora/linux/releases/23/Cloud/x86_64/Images/Fedora-Cloud-Base-Vagrant-23-20151030.x86_64.vagrant-libvirt.box"
    config.vm.provider :libvirt do |domain|
        domain.memory = 1024
    end

  config.vm.define "pki_server" do |server|
  end

  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/playbook.yml"
      ansible.groups = {
          "pki_server" => ["pki_server"],
      }
      #ansible.verbose = 'vv'
      ansible.extra_vars = {
          hostname: 'dogtag.example.org',
          domain: 'example.org',
          suffix: 'dc=example,dc=org',
          forwarder: '192.168.122.1',
          ldap_port: 389,
          http_port: 8080,
          https_port: 8443,
          pki_instance_name: 'pki-tomcat',
          security_domain: 'pki-tests',
          password: 'Secret123',
          vagrant_root: File.dirname(__FILE__)
      }
  end
end

