#!/bin/bash
set -e

. inventory/ipaenv

PROFILE="${IPA_INVENTORY}/firefoxprofile"

rm -rf "${PROFILE}"
mkdir "${PROFILE}"

cp "${IPA_INVENTORY}/prefs.js" "${PROFILE}/"
cp "${IPA_INVENTORY}/bookmarks.html" "${PROFILE}/"
cp "${IPA_INVENTORY}/xulstore.json" "${PROFILE}/"

certutil -N -d "${PROFILE}" --empty-password
certutil -A -d "${PROFILE}" -n 'IPA CA' -i "${IPA_INVENTORY}/ca.crt" -t "TC,C,T"

firefox -no-remote -profile "${PROFILE}" $@
